"use client";

import { useMemo } from "react";

interface FlexCardPreviewProps {
    summonerName: string;
    totalSkins: number;
    totalValue: number;
    topSkin: { name: string; price: number; image: string } | null;
}

export function FlexCardPreview({ summonerName, totalSkins, totalValue, topSkin }: FlexCardPreviewProps) {

    // Format value with commas
    const formattedValue = useMemo(() => {
        return new Intl.NumberFormat('en-US').format(totalValue);
    }, [totalValue]);

    return (
        <div
            id="flex-card-node"
            className="relative w-[800px] h-[418px] overflow-hidden bg-black text-white font-sans flex flex-col shadow-2xl"
            style={{
                background: 'linear-gradient(135deg, #1a1c2c 0%, #4a192c 100%)',
            }}
        >
            {/* Background Texture/Image Overlay */}
            <div
                className="absolute inset-0 opacity-40 bg-cover bg-center mix-blend-overlay transition-all duration-500"
                style={{
                    backgroundImage: `url('${topSkin?.image || "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg"}')`
                }}
            />

            {/* Content Container */}
            <div className="relative z-10 flex flex-col justify-between h-full p-8 border-4 border-amber-500/50">

                {/* Header */}
                <div className="flex justify-between items-start">
                    <div>
                        <h2 className="text-amber-400 font-bold text-xl tracking-widest uppercase">My Skins Collection</h2>
                        <h1 className="text-5xl font-extrabold mt-1 text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-amber-500 pb-2">
                            {summonerName || "Summoner"}
                        </h1>
                    </div>
                    {/* Badge / Brand */}
                    <div className="bg-black/40 backdrop-blur-md px-4 py-2 rounded-lg border border-white/10">
                        <span className="font-bold text-lg">mylolskins.com</span>
                    </div>
                </div>

                {/* Main Stats Row */}
                <div className="flex gap-8 items-end">
                    {/* Stat 1: Total Skins */}
                    <div className="flex-1 bg-black/40 backdrop-blur-lg p-6 rounded-xl border border-white/10">
                        <p className="text-gray-400 text-sm font-semibold uppercase tracking-wider">Total Collection Skins</p>
                        <p className="text-5xl font-black text-white mt-1">{totalSkins}</p>
                    </div>

                    {/* Stat 2: Collection Value */}
                    <div className="flex-1 bg-gradient-to-br from-amber-500/20 to-orange-600/20 backdrop-blur-lg p-6 rounded-xl border border-amber-500/30">
                        <p className="text-amber-200 text-sm font-semibold uppercase tracking-wider">Collection Value (RP)</p>
                        <p className="text-5xl font-black text-amber-500 mt-1">{formattedValue}</p>
                    </div>
                </div>

                {/* Footer / Top Skin Highlight */}
                <div className="flex justify-between items-end mt-4">
                    <div className="flex items-center gap-2 text-white/50 text-sm">
                        <span>Generated by mylolskins.com</span>
                    </div>

                    {/* Optional: Show "Top Skin" or Crown Jewel if available */}
                    {topSkin && (
                        <div className="text-right">
                            <p className="text-xs text-white/60 mb-1 uppercase tracking-wider">Crown Jewel</p>
                            <div className="flex items-center gap-3 bg-white/5 px-4 py-2 rounded-full border border-white/10">
                                <span className="font-bold text-amber-300">{topSkin.name}</span>
                                <span className="text-amber-500 font-bold text-sm bg-black/50 px-2 py-0.5 rounded">{topSkin.price} RP</span>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
